spring:
  application:
    name: ElevatorSystem

server:
  error:
    include-stacktrace: never

building:
  basementFloorsQuantity: 1
  regularFloorsQuantity: 50
  keycards:
    -1: _KEYCARD_-1
    49: _KEYCARD_49
  elevatorConfigs:
    - type: PUBLIC
      weightLimit: 1000
    - type: FREIGHT
      weightLimit: 3000